"""Added pipeline module

Revision ID: 8df750058cc3
Revises: c4d9cc6df9de
Create Date: 2025-08-18 16:38:10.109092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df750058cc3'
down_revision = 'c4d9cc6df9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
